### ISSUE TITLE
Change to semantic rules

### ISSUE THREAD

**Issue by bordi** [Mrackushka1/KPI-WEB-LR1#1]
https://github.com/Mrackushka1/KPI-WEB-LR1/blob/a8cf63f82e394d681547cf4862ea4c2a7d991173/LR-1.html#L16

Change to `nav>ul>li>a`

+

no need to wrap `|` with `a` tag

**Comment by Mrackushka1** [comment]
Changed it, but now I cannot do it without css =)

**Comment by bordi** [comment]
First lab is not meant to be with css 😉

**Comment by Mrackushka1** [comment]
Made an illogical list of one element with basic list marker on the left side of page and basic display: list-item ¯\\\_(ツ)_/¯
Now it's again better to make it even without `ul` > `li`

Previous "with css" code commented out

**Comment by bordi** [comment]
No, semantics it's how browser reads your html and also uses for a11y.

In this case menu is:
List of links of a site located in header, which is:
Nav>ul>li>a

**Comment by Mrackushka1** [comment]
So should I do it the way I've done it before, but without formatting list with css, so it will be ugly list in a column?
I wanted to make it look nice being in a row, how it's done in example...

**Comment by bordi** [comment]
> So should I do it the way I've done it before, but without formatting list with css, so it will be ugly list in a column? I wanted to make it look nice being in a row, how it's done in example...

It's not ugly. It's just pure html. The 1st lab was ab out only html and do not worry about its styling

**Comment by Mrackushka1** [comment]
Upd.
